import type { ColumnInfo, ConstraintInfo, Engine, ForeignKey, IndexInfo } from "../ipc/types";

export function quoteDdlIdentifier(engine: Engine, value: string): string {
  return engine === "mysql"
    ? "`" + value.replace(/`/g, "``") + "`"
    : '"' + value.replace(/"/g, '""') + '"';
}

function groupForeignKeys(foreignKeys: ForeignKey[]): ForeignKey[][] {
  const named = new Map<string, ForeignKey[]>();
  const groups: ForeignKey[][] = [];
  for (const fk of foreignKeys) {
    if (!fk.name) {
      groups.push([fk]);
      continue;
    }
    const current = named.get(fk.name) ?? [];
    current.push(fk);
    named.set(fk.name, current);
  }
  groups.push(...named.values());
  return groups;
}

function indexColumns(detail: string): string[] {
  if (!detail || /CREATE\s+(UNIQUE\s+)?INDEX/i.test(detail)) return [];
  const base = detail.split("·")[0].replace(/^origin:\s*\w+$/i, "").trim();
  if (!base) return [];
  return base
    .split(",")
    .map((value) => value.trim())
    .filter((value) => /^[A-Za-z_][A-Za-z0-9_$]*$/.test(value));
}

function isManagedIndex(engine: Engine, name: string): boolean {
  return name === "PRIMARY" || name.startsWith("sqlite_autoindex_") || (engine === "postgres" && name.endsWith("_pkey"));
}

function sqlString(value: string): string {
  return "'" + value.replace(/'/g, "''") + "'";
}

export function renderColumnDefault(engine: Engine, column: ColumnInfo): string | null {
  const value = column.defaultValue;
  if (value == null || value === "") return value === "" && engine === "mysql" ? "''" : null;
  if (engine !== "mysql") return value;

  const trimmed = value.trim();
  if (/^'.*'$/.test(trimmed) || /^".*"$/.test(trimmed)) return trimmed;
  if (/^(NULL|CURRENT_(?:TIMESTAMP|DATE|TIME)(?:\(\d+\))?|LOCALTIME(?:STAMP)?(?:\(\d+\))?)$/i.test(trimmed)) {
    return trimmed;
  }
  if (/^[A-Z_][A-Z0-9_]*\s*\([^)]*\)$/i.test(trimmed)) return trimmed;
  if (
    /\b(?:tinyint|smallint|mediumint|int|integer|bigint|decimal|numeric|float|double|real|bit|bool|boolean|year)\b/i.test(
      column.dataType,
    ) &&
    /^[-+]?\d+(?:\.\d+)?$/.test(trimmed)
  ) {
    return trimmed;
  }
  return sqlString(value);
}

export function buildSecondaryIndexStatements(
  engine: Engine,
  table: string,
  indexes: IndexInfo[] = [],
  constraints: ConstraintInfo[] = [],
): string[] {
  const q = (value: string) => quoteDdlIdentifier(engine, value);
  const constraintOwnedIndexes = new Set(
    constraints
      .filter((constraint) => constraint.kind === "primary" || constraint.kind === "unique")
      .map((constraint) => constraint.name)
      .filter((name): name is string => !!name),
  );
  const secondary = indexes.filter(
    (index) => !isManagedIndex(engine, index.name) && !constraintOwnedIndexes.has(index.name),
  );
  return secondary.map((index) => {
    const definition = index.detail.trim();
    if (engine === "postgres" && /^CREATE\s+(UNIQUE\s+)?INDEX/i.test(definition)) {
      return definition.replace(/;?\s*$/, ";");
    }
    const cols = indexColumns(definition);
    if (cols.length) {
      return `CREATE ${index.unique ? "UNIQUE " : ""}INDEX ${q(index.name)} ON ${q(table)} (${cols
        .map(q)
        .join(", ")});`;
    }
    return `-- Index ${q(index.name)}${index.unique ? " (UNIQUE)" : ""} exists, but its exact column/expression definition was not available from metadata.`;
  });
}

function renderColumnExtra(engine: Engine, column: ColumnInfo): string[] {
  const extra = column.extra?.trim() ?? "";
  if (!extra) return [];

  if (engine === "postgres") {
    if (/IDENTITY ALWAYS/i.test(extra)) return ["GENERATED ALWAYS AS IDENTITY"];
    if (/IDENTITY BY DEFAULT/i.test(extra)) return ["GENERATED BY DEFAULT AS IDENTITY"];
    return [];
  }

  if (engine === "mysql") {
    const parts: string[] = [];
    if (/\bauto_increment\b/i.test(extra)) parts.push("AUTO_INCREMENT");
    const onUpdate = extra.match(/\bon update\s+(.+)$/i);
    if (onUpdate?.[1]) parts.push(`ON UPDATE ${onUpdate[1].trim()}`);
    return parts;
  }

  return [];
}

export function buildTableDdl(
  engine: Engine,
  table: string,
  columns: ColumnInfo[],
  foreignKeys: ForeignKey[] = [],
  indexes: IndexInfo[] = [],
  constraints: ConstraintInfo[] = [],
): string {
  const q = (value: string) => quoteDdlIdentifier(engine, value);
  if (!columns.length) return `-- No column information available for ${table}`;

  const primaryKeys = columns.filter((column) => column.isPrimaryKey);
  const defs = columns.map((column) => {
    let line = `  ${q(column.name)} ${column.dataType || "TEXT"}`;
    const identity = engine === "postgres" && /IDENTITY/i.test(column.extra ?? "");
    if (column.generated && !column.generated.includes("expression unavailable")) {
      if (engine === "postgres") line += ` GENERATED ALWAYS AS (${column.generated}) STORED`;
      else if (engine === "mysql") {
        line += ` GENERATED ALWAYS AS (${column.generated})`;
        line += /STORED GENERATED/i.test(column.extra ?? "") ? " STORED" : " VIRTUAL";
      }
    } else if (identity) {
      const extra = renderColumnExtra(engine, column);
      if (extra.length) line += ` ${extra.join(" ")}`;
    } else {
      const defaultSql = renderColumnDefault(engine, column);
      if (defaultSql != null) line += ` DEFAULT ${defaultSql}`;
    }
    if (primaryKeys.length === 1 && column.isPrimaryKey) line += " PRIMARY KEY";
    else if (!column.nullable) line += " NOT NULL";
    if (!column.generated && !identity) {
      const extra = renderColumnExtra(engine, column);
      if (extra.length) line += ` ${extra.join(" ")}`;
    }
    if (engine === "mysql" && column.comment) line += ` COMMENT ${sqlString(column.comment)}`;
    return line;
  });

  if (primaryKeys.length > 1) {
    defs.push(`  PRIMARY KEY (${primaryKeys.map((column) => q(column.name)).join(", ")})`);
  }

  for (const constraint of constraints.filter((item) => item.kind !== "primary")) {
    const definition = constraint.definition.trim();
    if (!definition) continue;
    const prefix = constraint.name ? `CONSTRAINT ${q(constraint.name)} ` : "";
    defs.push(`  ${prefix}${definition}`);
  }

  const tableFks = foreignKeys.filter((fk) => fk.table === table);
  for (const group of groupForeignKeys(tableFks)) {
    const first = group[0];
    const local = group.map((fk) => q(fk.column)).join(", ");
    const remote = group.map((fk) => q(fk.refColumn)).join(", ");
    const constraint = first.name ? `CONSTRAINT ${q(first.name)} ` : "";
    defs.push(
      `  ${constraint}FOREIGN KEY (${local}) REFERENCES ${q(first.refTable)} (${remote})`,
    );
  }

  const statements = [
    `-- Generated from OrbitoDB schema metadata for ${engine}.`,
    "-- Triggers and engine-specific table/storage options may still require review.",
    `CREATE TABLE ${q(table)} (`,
    defs.join(",\n"),
    ");",
  ];

  const unavailableGenerated = columns.filter(
    (column) => column.generated?.includes("expression unavailable"),
  );
  if (unavailableGenerated.length) {
    statements.push("", "-- Generated columns requiring manual review");
    for (const column of unavailableGenerated) {
      statements.push(
        `-- ${q(column.name)} is ${column.generated}; SQLite metadata does not expose the original expression.`,
      );
    }
  }

  const commented = columns.filter((column) => column.comment);
  if (commented.length && engine === "postgres") {
    statements.push("", "-- Column comments");
    for (const column of commented) {
      statements.push(
        `COMMENT ON COLUMN ${q(table)}.${q(column.name)} IS ${sqlString(column.comment ?? "")};`,
      );
    }
  } else if (commented.length && engine === "sqlite") {
    statements.push("", "-- Column comments (SQLite does not persist native column comments)");
    for (const column of commented) {
      statements.push(`-- ${q(column.name)}: ${column.comment}`);
    }
  }

  const secondaryStatements = buildSecondaryIndexStatements(engine, table, indexes, constraints);
  if (secondaryStatements.length) statements.push("", "-- Secondary indexes", ...secondaryStatements);

  return statements.join("\n");
}
