import type { ColumnInfo, Engine } from "../ipc/types";

export interface DuplicateProjection {
  columns: string[];
  values: unknown[];
  omitted: string[];
}

function autoGeneratedPrimaryKey(engine: Engine, column: ColumnInfo): boolean {
  if (!column.isPrimaryKey) return false;
  if (column.generated?.trim()) return true;
  if (column.defaultValue?.trim()) return true;
  const extra = column.extra?.toLowerCase() ?? "";
  if (/auto_increment|identity|generated/.test(extra)) return true;
  if (engine === "sqlite" && column.dataType.trim().toUpperCase() === "INTEGER") return true;
  return false;
}

function generatedColumn(column: ColumnInfo): boolean {
  return !!column.generated?.trim() || /generated/i.test(column.extra ?? "");
}

export function buildDuplicateProjection(
  engine: Engine,
  columns: ColumnInfo[],
  rowColumns: string[],
  row: unknown[],
): DuplicateProjection {
  const byName = new Map(columns.map((column) => [column.name, column]));
  const outColumns: string[] = [];
  const values: unknown[] = [];
  const omitted: string[] = [];
  const unsafePrimaryKeys: string[] = [];

  rowColumns.forEach((name, index) => {
    const info = byName.get(name);
    if (!info) {
      outColumns.push(name);
      values.push(row[index]);
      return;
    }

    if (generatedColumn(info)) {
      omitted.push(name);
      return;
    }

    if (info.isPrimaryKey) {
      if (autoGeneratedPrimaryKey(engine, info)) {
        omitted.push(name);
        return;
      }
      unsafePrimaryKeys.push(name);
      return;
    }

    outColumns.push(name);
    values.push(row[index]);
  });

  if (unsafePrimaryKeys.length) {
    throw new Error(
      `Cannot safely duplicate rows with manually assigned primary key${unsafePrimaryKeys.length === 1 ? "" : "s"}: ${unsafePrimaryKeys.join(", ")}. Create a new row and choose a new key instead.`,
    );
  }

  if (!outColumns.length) {
    throw new Error("No insertable columns remain after generated columns are excluded.");
  }

  return { columns: outColumns, values, omitted };
}
