import { describe, expect, it } from "vitest";
import type { ColumnDef } from "../ipc/types";
import {
  columnTypeError,
  createTableSqlPreview,
  hasTableDesignIssues,
  normalizeDataType,
  schemaIdentifierError,
  supportsAutoIncrement,
  tableDesignIssues,
} from "./schemaDesign";

const columns: ColumnDef[] = [
  { name: "id", dataType: "INTEGER", nullable: false, primaryKey: true, autoIncrement: true },
  { name: "display_name", dataType: "VARCHAR(255)", nullable: false, primaryKey: false },
];

describe("schema design", () => {
  it("validates portable table and column identifiers", () => {
    expect(schemaIdentifierError("audit_events", "table")).toBeNull();
    expect(schemaIdentifierError("2026_events", "table")).toMatch(/start with/i);
    expect(schemaIdentifierError("display-name", "column")).toMatch(/underscores/i);
  });

  it("normalizes and validates safe SQL data types", () => {
    expect(normalizeDataType(" decimal ( 10, 2 ) ")).toBe("DECIMAL(10,2)");
    expect(columnTypeError("TIMESTAMP WITH TIME ZONE")).toBeNull();
    expect(columnTypeError("TEXT); DROP TABLE users; --")).toMatch(/SQL type/i);
    expect(columnTypeError("DECIMAL(2,8)")).toMatch(/scale/i);
  });

  it("limits auto-increment to compatible integer types", () => {
    expect(supportsAutoIncrement("sqlite", "INTEGER")).toBe(true);
    expect(supportsAutoIncrement("sqlite", "BIGINT")).toBe(false);
    expect(supportsAutoIncrement("postgres", "BIGINT")).toBe(true);
    expect(supportsAutoIncrement("mysql", "VARCHAR(255)")).toBe(false);
  });

  it("finds duplicate objects and duplicate columns", () => {
    const issues = tableDesignIssues("sqlite", "events", [columns[0], { ...columns[1], name: "ID" }], ["events"]);
    expect(issues.tableName).toMatch(/already uses/i);
    expect(issues.columnNames[1]).toMatch(/unique/i);
    expect(hasTableDesignIssues(issues)).toBe(true);
  });

  it("requires auto-increment columns to be primary keys", () => {
    const issues = tableDesignIssues("postgres", "events", [
      { name: "id", dataType: "BIGINT", nullable: false, primaryKey: false, autoIncrement: true },
    ]);
    expect(issues.form).toMatch(/integer primary key/i);
  });

  it("builds engine-aware SQL previews", () => {
    expect(createTableSqlPreview("sqlite", "events", columns)).toContain('"id" INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(createTableSqlPreview("postgres", "events", columns)).toContain("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    expect(createTableSqlPreview("mysql", "events", columns)).toContain("`events`");
  });
});
