import type { ColumnDef, Engine } from "../ipc/types";
import { quoteIdentifier } from "./sql";

const IDENTIFIER_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;
const DATA_TYPE_PATTERN = /^[A-Za-z][A-Za-z0-9_]*(?:\s+[A-Za-z][A-Za-z0-9_]*){0,3}(?:\(\d{1,5}(?:,\d{1,5})?\))?$/;

export interface TableDesignIssues {
  columnNames: Array<string | null>;
  columnTypes: Array<string | null>;
  form: string | null;
  tableName: string | null;
}

export function schemaIdentifierError(value: string, subject: "table" | "column"): string | null {
  const name = value.trim();
  const label = subject === "table" ? "table" : "column";
  if (!name) return `Enter a ${label} name.`;
  if (name.length > 63) return "Use 63 characters or fewer.";
  if (!IDENTIFIER_PATTERN.test(name)) {
    return "Start with a letter or underscore, then use only letters, numbers, and underscores.";
  }
  return null;
}

export function normalizeDataType(value: string): string {
  return value
    .trim()
    .replace(/\s+/g, " ")
    .replace(/\s*\(\s*/g, "(")
    .replace(/\s*,\s*/g, ",")
    .replace(/\s*\)\s*/g, ")")
    .toUpperCase();
}

export function columnTypeError(value: string): string | null {
  const type = normalizeDataType(value);
  if (!type) return "Choose a data type.";
  if (type.length > 48) return "Use 48 characters or fewer.";
  if (!DATA_TYPE_PATTERN.test(type)) {
    return "Use a SQL type such as TEXT, VARCHAR(255), or DECIMAL(10,2).";
  }
  const parameters = /\((\d+)(?:,(\d+))?\)$/.exec(type);
  if (parameters) {
    const precision = Number(parameters[1]);
    const scale = parameters[2] == null ? null : Number(parameters[2]);
    if (precision < 1) return "Type size must be at least 1.";
    if (scale != null && scale > precision) return "Decimal scale cannot exceed precision.";
  }
  return null;
}

export function supportsAutoIncrement(engine: Engine, dataType: string): boolean {
  const type = normalizeDataType(dataType).replace(/\(.+\)$/, "");
  if (engine === "sqlite") return type === "INTEGER";
  if (engine === "postgres") return ["SMALLINT", "INTEGER", "BIGINT"].includes(type);
  return ["TINYINT", "SMALLINT", "MEDIUMINT", "INT", "INTEGER", "BIGINT"].includes(type);
}

export function tableDesignIssues(
  engine: Engine,
  tableName: string,
  columns: ColumnDef[],
  existingNames: string[] = [],
): TableDesignIssues {
  let tableNameIssue = schemaIdentifierError(tableName, "table");
  const normalizedTable = tableName.trim().toLocaleLowerCase();
  if (!tableNameIssue && existingNames.some((name) => name.toLocaleLowerCase() === normalizedTable)) {
    tableNameIssue = "A table or view already uses this name.";
  }

  const seen = new Set<string>();
  const columnNames = columns.map((column) => {
    const issue = schemaIdentifierError(column.name, "column");
    const normalized = column.name.trim().toLocaleLowerCase();
    if (issue) return issue;
    if (seen.has(normalized)) return "Column names must be unique.";
    seen.add(normalized);
    return null;
  });
  const columnTypes = columns.map((column) => columnTypeError(column.dataType));

  let form: string | null = null;
  if (columns.length === 0) form = "Add at least one column.";
  else if (columns.filter((column) => column.primaryKey).length > 1) form = "Choose one primary key column.";
  else {
    const incompatible = columns.find(
      (column) => column.autoIncrement && (!column.primaryKey || !supportsAutoIncrement(engine, column.dataType)),
    );
    if (incompatible) form = "Auto-increment requires a compatible integer primary key.";
  }

  return { tableName: tableNameIssue, columnNames, columnTypes, form };
}

export function hasTableDesignIssues(issues: TableDesignIssues): boolean {
  return !!issues.tableName || !!issues.form || issues.columnNames.some(Boolean) || issues.columnTypes.some(Boolean);
}

export function dataTypeOptions(engine: Engine): string[] {
  if (engine === "postgres") {
    return ["BIGINT", "INTEGER", "TEXT", "VARCHAR(255)", "BOOLEAN", "NUMERIC(10,2)", "DATE", "TIMESTAMP", "JSONB", "UUID"];
  }
  if (engine === "mysql") {
    return ["BIGINT", "INT", "VARCHAR(255)", "TEXT", "DECIMAL(10,2)", "BOOLEAN", "DATE", "DATETIME", "JSON", "BLOB"];
  }
  return ["INTEGER", "TEXT", "REAL", "NUMERIC", "BLOB"];
}

export function createTableSqlPreview(engine: Engine, tableName: string, columns: ColumnDef[]): string {
  const table = tableName.trim() || "table_name";
  const definitions = columns.map((column, index) => {
    const name = column.name.trim() || `column_${index + 1}`;
    const type = normalizeDataType(column.dataType) || "TEXT";
    const parts = [quoteIdentifier(name, engine), type];

    if (column.autoIncrement && engine === "postgres") parts.push("GENERATED BY DEFAULT AS IDENTITY");
    if (column.autoIncrement && engine === "mysql") parts.push("AUTO_INCREMENT");
    if (column.primaryKey) parts.push("PRIMARY KEY");
    else if (!column.nullable) parts.push("NOT NULL");
    if (column.autoIncrement && engine === "sqlite") parts.push("AUTOINCREMENT");
    return `  ${parts.join(" ")}`;
  });
  return `CREATE TABLE ${quoteIdentifier(table, engine)} (\n${definitions.join(",\n")}\n);`;
}
